-- MySQL Script generated by MySQL Workbench
-- Thu Dec  7 22:46:59 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pizzaria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizzaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzaria` DEFAULT CHARACTER SET utf8 ;
USE `pizzaria` ;

-- -----------------------------------------------------
-- Table `pizzaria`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`endereco` (
  `idendereco` INT NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `referencial` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idendereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`clientes` (
  `idclientes` INT NOT NULL AUTO_INCREMENT,
  `primeironome` VARCHAR(45) NULL,
  `sobrenome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `celular` VARCHAR(45) NULL,
  `genero` VARCHAR(45) NULL,
  `endereco_idendereco` INT NOT NULL,
  PRIMARY KEY (`idclientes`, `endereco_idendereco`),
  INDEX `fk_clientes_endereco_idx` (`endereco_idendereco` ASC) VISIBLE,
  CONSTRAINT `fk_clientes_endereco`
    FOREIGN KEY (`endereco_idendereco`)
    REFERENCES `pizzaria`.`endereco` (`idendereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`pizza` (
  `idpizza` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `preco` DOUBLE NOT NULL,
  `personalizada` TINYINT NULL,
  PRIMARY KEY (`idpizza`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`Tamanho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`Tamanho` (
  `idTamanho` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idTamanho`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`fornada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`fornada` (
  `idfornada` INT NOT NULL,
  `numfornada` INT NULL,
  `quantidade` INT NULL,
  PRIMARY KEY (`idfornada`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`acompanhamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`acompanhamento` (
  `idacompanhamento` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `preco` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idacompanhamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`acompanhamentoPedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`acompanhamentoPedido` (
  `idacompanhamentoPedido` INT NOT NULL,
  `quantidade` VARCHAR(45) NOT NULL,
  `acompanhamento_idacompanhamento` INT NOT NULL,
  PRIMARY KEY (`idacompanhamentoPedido`, `quantidade`, `acompanhamento_idacompanhamento`),
  INDEX `fk_acompanhamentoPedido_acompanhamento1_idx` (`acompanhamento_idacompanhamento` ASC) VISIBLE,
  CONSTRAINT `fk_acompanhamentoPedido_acompanhamento1`
    FOREIGN KEY (`acompanhamento_idacompanhamento`)
    REFERENCES `pizzaria`.`acompanhamento` (`idacompanhamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`Pedido` (
  `idPedido` INT NOT NULL,
  `datahora` DATE NULL,
  `clientes_idclientes` INT NOT NULL,
  `clientes_endereco_idendereco` INT NOT NULL,
  `fornada_idfornada` INT NOT NULL,
  `acompanhamentoPedido_idacompanhamentoPedido` INT NOT NULL,
  `acompanhamentoPedido_quantidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPedido`, `acompanhamentoPedido_idacompanhamentoPedido`, `acompanhamentoPedido_quantidade`),
  INDEX `fk_Pedido_clientes1_idx` (`clientes_idclientes` ASC, `clientes_endereco_idendereco` ASC) VISIBLE,
  INDEX `fk_Pedido_fornada1_idx` (`fornada_idfornada` ASC) VISIBLE,
  INDEX `fk_Pedido_acompanhamentoPedido1_idx` (`acompanhamentoPedido_idacompanhamentoPedido` ASC, `acompanhamentoPedido_quantidade` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_clientes1`
    FOREIGN KEY (`clientes_idclientes` , `clientes_endereco_idendereco`)
    REFERENCES `pizzaria`.`clientes` (`idclientes` , `endereco_idendereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_fornada1`
    FOREIGN KEY (`fornada_idfornada`)
    REFERENCES `pizzaria`.`fornada` (`idfornada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_acompanhamentoPedido1`
    FOREIGN KEY (`acompanhamentoPedido_idacompanhamentoPedido` , `acompanhamentoPedido_quantidade`)
    REFERENCES `pizzaria`.`acompanhamentoPedido` (`idacompanhamentoPedido` , `quantidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`Ingrediente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`Ingrediente` (
  `idIngrediente` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `preco` FLOAT NOT NULL,
  PRIMARY KEY (`idIngrediente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`pizzaPedida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`pizzaPedida` (
  `idpizzaPedida` INT NOT NULL,
  `quantidade` VARCHAR(45) NOT NULL,
  `pizza_idpizza` INT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  `Tamanho_idTamanho` INT NOT NULL,
  PRIMARY KEY (`idpizzaPedida`),
  INDEX `fk_pizzaPedida_pizza1_idx` (`pizza_idpizza` ASC) VISIBLE,
  INDEX `fk_pizzaPedida_Pedido1_idx` (`Pedido_idPedido` ASC) VISIBLE,
  INDEX `fk_pizzaPedida_Tamanho1_idx` (`Tamanho_idTamanho` ASC) VISIBLE,
  CONSTRAINT `fk_pizzaPedida_pizza1`
    FOREIGN KEY (`pizza_idpizza`)
    REFERENCES `pizzaria`.`pizza` (`idpizza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pizzaPedida_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `pizzaria`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pizzaPedida_Tamanho1`
    FOREIGN KEY (`Tamanho_idTamanho`)
    REFERENCES `pizzaria`.`Tamanho` (`idTamanho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaria`.`pizzaPedida_has_Ingrediente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`pizzaPedida_has_Ingrediente` (
  `pizzaPedida_idpizzaPedida` INT NOT NULL,
  `Ingrediente_idIngrediente` INT NOT NULL,
  PRIMARY KEY (`pizzaPedida_idpizzaPedida`, `Ingrediente_idIngrediente`),
  INDEX `fk_pizzaPedida_has_Ingrediente_Ingrediente1_idx` (`Ingrediente_idIngrediente` ASC) VISIBLE,
  INDEX `fk_pizzaPedida_has_Ingrediente_pizzaPedida1_idx` (`pizzaPedida_idpizzaPedida` ASC) VISIBLE,
  CONSTRAINT `fk_pizzaPedida_has_Ingrediente_pizzaPedida1`
    FOREIGN KEY (`pizzaPedida_idpizzaPedida`)
    REFERENCES `pizzaria`.`pizzaPedida` (`idpizzaPedida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pizzaPedida_has_Ingrediente_Ingrediente1`
    FOREIGN KEY (`Ingrediente_idIngrediente`)
    REFERENCES `pizzaria`.`Ingrediente` (`idIngrediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
